### ISSUE TITLE
HTML styling in qNotes

### ISSUE THREAD

**Issue by bkepl** [p0cisk/qNote#2]
This would be a very nice option. I am thinking of only the most basic formatting tags being available: headings, paragraph, hyperlink, numbered and bulleted lists (and sublists), and bold/italic.

Also text wrap would be a welcome addition.

**Comment by MiraGeowerkstatt** [comment]
We would like to fix this Issue and include an additional dialog to add hyperlinks pointing to urls or the file system (see screenshot). @p0cisk  would you be willing to review a pull request implementing these changes?

![image](https://user-images.githubusercontent.com/49144408/117982759-9f784f80-b336-11eb-85d1-f9d628e1e49c.png)

**Comment by p0cisk** [comment]
@MiraGeowerkstatt Yes, please add pull request to this repo and I will review it and apply to master.

**Comment by p0cisk** [comment]
I've merged your pull request but I have to do some tweaks and test for backward compatibility. After that I will publish new version. Thanks for help

**Comment by MiraGeowerkstatt** [comment]
> I've merged your pull request but I have to do some tweaks and test for backward compatibility. After that I will publish new version. Thanks for help

Great! Thanks very much for reviewing and the adaptations.

**Comment by bkepl** [comment]
Sorry!, I've missed the replies. Is there any way I can help at this point?

**Comment by bkepl** [comment]
I'm happy to see this is being considered for an already-useful tool!

**Comment by bkepl** [comment]
Curious - any idea of a timeline?

**Comment by MiraGeowerkstatt** [comment]
@bkepl It has allready been added, try downloading the new version of the plugin.

**Comment by bkepl** [comment]
Well, not sure how I missed this; guess I haven't used it in a while. Very nice!

Even more than formatting headings, word wrap would be awesome.
