### ISSUE TITLE
Hyperlink-Text is inserted into existing text when adding a hyperlink from the context menu.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [p0cisk/qNote#4]
@p0cisk thanks a lot for your great additions to the text formatting! That makes this plugin nice and easy to use.
Unfortunately I discovered just now that I made a mistake in by contribution which leads to a
 bug (see screenshots below). It only occurs when the hyperlink is added from the context menu.
It is a small fix and I would like to submit a pull request, but the released version of qNote which I get from installing it via QGis seems to be ahead of this master branch, is that possible?
Would you link me to include the merge in my fix? 

![Bild1](https://user-images.githubusercontent.com/49144408/120353544-07043800-c302-11eb-8684-59756a27eb62.png)

![Bild2](https://user-images.githubusercontent.com/49144408/120353570-0e2b4600-c302-11eb-824c-3bb8cfeb3411.png)

![Bild3](https://user-images.githubusercontent.com/49144408/120353583-108da000-c302-11eb-86c7-3a508de82cc8.png)

![Bild4](https://user-images.githubusercontent.com/49144408/120353591-11becd00-c302-11eb-8317-7dabca4d4a01.png)

**Comment by p0cisk** [comment]
Thanks for fix. Could you merge master to your pull request, because there are some conflicts.

**Comment by MiraGeowerkstatt** [comment]
> Thanks for fix. Could you merge master to your pull request, because there are some conflicts.

Thanks, I merged the master branch (sorry for the delay, i was out of the office).

**Comment by p0cisk** [comment]
Nice work, thanks. I've pushed version 2.2, should be available soon in official repository.
