### ISSUE TITLE
mouse pointer does not change the icon when enlarge an open window

### ISSUE THREAD

**Issue by ZsanettMed** [p0cisk/qNote#6]
Hey, 
I would like to report the following issue: if the plugin QNote is installed, the mouse pointer does not change the icon when enlarge an open window.
QGIS Version: 3.28.4 on Windows

![Mauszeiger](https://user-images.githubusercontent.com/83091224/235855431-c5c0de6c-89dc-4901-9396-375a700e2791.gif)

Best regards, 
Zsanett

**Comment by p0cisk** [comment]
Should be fixed in version 2.3
